/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRegisterImport } from './routes/auth_.register'
import { Route as AuthLoginImport } from './routes/auth_.login'
import { Route as LayoutTeacherImport } from './routes/_layout.teacher'
import { Route as LayoutStudentImport } from './routes/_layout.student'
import { Route as LayoutCuratorImport } from './routes/_layout.curator'
import { Route as LayoutAdminImport } from './routes/_layout.admin'
import { Route as LayoutTeacherIndexImport } from './routes/_layout.teacher.index'
import { Route as LayoutStudentIndexImport } from './routes/_layout.student.index'
import { Route as LayoutTeacherScheduleImport } from './routes/_layout.teacher.schedule'
import { Route as LayoutTeacherCoursesImport } from './routes/_layout.teacher.courses'
import { Route as LayoutStudentNotificationsImport } from './routes/_layout.student_.notifications'
import { Route as LayoutStudentShopImport } from './routes/_layout.student.shop'
import { Route as LayoutStudentScheduleImport } from './routes/_layout.student.schedule'
import { Route as LayoutCuratorNotificationsImport } from './routes/_layout.curator_.notifications'
import { Route as LayoutStudentEducationIndexImport } from './routes/_layout.student.education.index'
import { Route as LayoutTeacherCoursesCourseImport } from './routes/_layout.teacher.courses.$course'
import { Route as LayoutCuratorCourseLessonImport } from './routes/_layout.curator.$course.$lesson'
import { Route as LayoutStudentEducationCourseIndexImport } from './routes/_layout.student.education.$course.index'
import { Route as LayoutStudentEducationCourseLessonImport } from './routes/_layout.student.education.$course.$lesson'
import { Route as LayoutCuratorCourseLessonHomeworksImport } from './routes/_layout.curator_.$course.$lesson.homeworks'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTeacherRoute = LayoutTeacherImport.update({
  path: '/teacher',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStudentRoute = LayoutStudentImport.update({
  path: '/student',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCuratorRoute = LayoutCuratorImport.update({
  path: '/curator',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeacherIndexRoute = LayoutTeacherIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTeacherRoute,
} as any)

const LayoutStudentIndexRoute = LayoutStudentIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutStudentRoute,
} as any)

const LayoutTeacherScheduleRoute = LayoutTeacherScheduleImport.update({
  path: '/schedule',
  getParentRoute: () => LayoutTeacherRoute,
} as any)

const LayoutTeacherCoursesRoute = LayoutTeacherCoursesImport.update({
  path: '/courses',
  getParentRoute: () => LayoutTeacherRoute,
} as any)

const LayoutStudentNotificationsRoute = LayoutStudentNotificationsImport.update(
  {
    path: '/student/notifications',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutStudentShopRoute = LayoutStudentShopImport.update({
  path: '/shop',
  getParentRoute: () => LayoutStudentRoute,
} as any)

const LayoutStudentScheduleRoute = LayoutStudentScheduleImport.update({
  path: '/schedule',
  getParentRoute: () => LayoutStudentRoute,
} as any)

const LayoutCuratorNotificationsRoute = LayoutCuratorNotificationsImport.update(
  {
    path: '/curator/notifications',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutStudentEducationIndexRoute =
  LayoutStudentEducationIndexImport.update({
    path: '/education/',
    getParentRoute: () => LayoutStudentRoute,
  } as any)

const LayoutTeacherCoursesCourseRoute = LayoutTeacherCoursesCourseImport.update(
  {
    path: '/$course',
    getParentRoute: () => LayoutTeacherCoursesRoute,
  } as any,
)

const LayoutCuratorCourseLessonRoute = LayoutCuratorCourseLessonImport.update({
  path: '/$course/$lesson',
  getParentRoute: () => LayoutCuratorRoute,
} as any)

const LayoutStudentEducationCourseIndexRoute =
  LayoutStudentEducationCourseIndexImport.update({
    path: '/education/$course/',
    getParentRoute: () => LayoutStudentRoute,
  } as any)

const LayoutStudentEducationCourseLessonRoute =
  LayoutStudentEducationCourseLessonImport.update({
    path: '/education/$course/$lesson',
    getParentRoute: () => LayoutStudentRoute,
  } as any)

const LayoutCuratorCourseLessonHomeworksRoute =
  LayoutCuratorCourseLessonHomeworksImport.update({
    path: '/curator/$course/$lesson/homeworks',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/curator': {
      id: '/_layout/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof LayoutCuratorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/student': {
      id: '/_layout/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof LayoutStudentImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/teacher': {
      id: '/_layout/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof LayoutTeacherImport
      parentRoute: typeof LayoutImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_layout/curator/notifications': {
      id: '/_layout/curator/notifications'
      path: '/curator/notifications'
      fullPath: '/curator/notifications'
      preLoaderRoute: typeof LayoutCuratorNotificationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/student/schedule': {
      id: '/_layout/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof LayoutStudentScheduleImport
      parentRoute: typeof LayoutStudentImport
    }
    '/_layout/student/shop': {
      id: '/_layout/student/shop'
      path: '/shop'
      fullPath: '/student/shop'
      preLoaderRoute: typeof LayoutStudentShopImport
      parentRoute: typeof LayoutStudentImport
    }
    '/_layout/student/notifications': {
      id: '/_layout/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof LayoutStudentNotificationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/teacher/courses': {
      id: '/_layout/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof LayoutTeacherCoursesImport
      parentRoute: typeof LayoutTeacherImport
    }
    '/_layout/teacher/schedule': {
      id: '/_layout/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof LayoutTeacherScheduleImport
      parentRoute: typeof LayoutTeacherImport
    }
    '/_layout/student/': {
      id: '/_layout/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof LayoutStudentIndexImport
      parentRoute: typeof LayoutStudentImport
    }
    '/_layout/teacher/': {
      id: '/_layout/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof LayoutTeacherIndexImport
      parentRoute: typeof LayoutTeacherImport
    }
    '/_layout/curator/$course/$lesson': {
      id: '/_layout/curator/$course/$lesson'
      path: '/$course/$lesson'
      fullPath: '/curator/$course/$lesson'
      preLoaderRoute: typeof LayoutCuratorCourseLessonImport
      parentRoute: typeof LayoutCuratorImport
    }
    '/_layout/teacher/courses/$course': {
      id: '/_layout/teacher/courses/$course'
      path: '/$course'
      fullPath: '/teacher/courses/$course'
      preLoaderRoute: typeof LayoutTeacherCoursesCourseImport
      parentRoute: typeof LayoutTeacherCoursesImport
    }
    '/_layout/student/education/': {
      id: '/_layout/student/education/'
      path: '/education'
      fullPath: '/student/education'
      preLoaderRoute: typeof LayoutStudentEducationIndexImport
      parentRoute: typeof LayoutStudentImport
    }
    '/_layout/curator/$course/$lesson/homeworks': {
      id: '/_layout/curator/$course/$lesson/homeworks'
      path: '/curator/$course/$lesson/homeworks'
      fullPath: '/curator/$course/$lesson/homeworks'
      preLoaderRoute: typeof LayoutCuratorCourseLessonHomeworksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/student/education/$course/$lesson': {
      id: '/_layout/student/education/$course/$lesson'
      path: '/education/$course/$lesson'
      fullPath: '/student/education/$course/$lesson'
      preLoaderRoute: typeof LayoutStudentEducationCourseLessonImport
      parentRoute: typeof LayoutStudentImport
    }
    '/_layout/student/education/$course/': {
      id: '/_layout/student/education/$course/'
      path: '/education/$course'
      fullPath: '/student/education/$course'
      preLoaderRoute: typeof LayoutStudentEducationCourseIndexImport
      parentRoute: typeof LayoutStudentImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAdminRoute,
    LayoutCuratorRoute: LayoutCuratorRoute.addChildren({
      LayoutCuratorCourseLessonRoute,
    }),
    LayoutStudentRoute: LayoutStudentRoute.addChildren({
      LayoutStudentScheduleRoute,
      LayoutStudentShopRoute,
      LayoutStudentIndexRoute,
      LayoutStudentEducationIndexRoute,
      LayoutStudentEducationCourseLessonRoute,
      LayoutStudentEducationCourseIndexRoute,
    }),
    LayoutTeacherRoute: LayoutTeacherRoute.addChildren({
      LayoutTeacherCoursesRoute: LayoutTeacherCoursesRoute.addChildren({
        LayoutTeacherCoursesCourseRoute,
      }),
      LayoutTeacherScheduleRoute,
      LayoutTeacherIndexRoute,
    }),
    LayoutCuratorNotificationsRoute,
    LayoutStudentNotificationsRoute,
    LayoutCuratorCourseLessonHomeworksRoute,
  }),
  AuthLoginRoute,
  AuthRegisterRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin",
        "/_layout/curator",
        "/_layout/student",
        "/_layout/teacher",
        "/_layout/curator/notifications",
        "/_layout/student/notifications",
        "/_layout/curator/$course/$lesson/homeworks"
      ]
    },
    "/_layout/admin": {
      "filePath": "_layout.admin.tsx",
      "parent": "/_layout"
    },
    "/_layout/curator": {
      "filePath": "_layout.curator.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/curator/$course/$lesson"
      ]
    },
    "/_layout/student": {
      "filePath": "_layout.student.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/student/schedule",
        "/_layout/student/shop",
        "/_layout/student/",
        "/_layout/student/education/",
        "/_layout/student/education/$course/$lesson",
        "/_layout/student/education/$course/"
      ]
    },
    "/_layout/teacher": {
      "filePath": "_layout.teacher.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/teacher/courses",
        "/_layout/teacher/schedule",
        "/_layout/teacher/"
      ]
    },
    "/auth/login": {
      "filePath": "auth_.login.tsx"
    },
    "/auth/register": {
      "filePath": "auth_.register.tsx"
    },
    "/_layout/curator/notifications": {
      "filePath": "_layout.curator_.notifications.tsx",
      "parent": "/_layout"
    },
    "/_layout/student/schedule": {
      "filePath": "_layout.student.schedule.tsx",
      "parent": "/_layout/student"
    },
    "/_layout/student/shop": {
      "filePath": "_layout.student.shop.tsx",
      "parent": "/_layout/student"
    },
    "/_layout/student/notifications": {
      "filePath": "_layout.student_.notifications.tsx",
      "parent": "/_layout"
    },
    "/_layout/teacher/courses": {
      "filePath": "_layout.teacher.courses.tsx",
      "parent": "/_layout/teacher",
      "children": [
        "/_layout/teacher/courses/$course"
      ]
    },
    "/_layout/teacher/schedule": {
      "filePath": "_layout.teacher.schedule.tsx",
      "parent": "/_layout/teacher"
    },
    "/_layout/student/": {
      "filePath": "_layout.student.index.tsx",
      "parent": "/_layout/student"
    },
    "/_layout/teacher/": {
      "filePath": "_layout.teacher.index.tsx",
      "parent": "/_layout/teacher"
    },
    "/_layout/curator/$course/$lesson": {
      "filePath": "_layout.curator.$course.$lesson.tsx",
      "parent": "/_layout/curator"
    },
    "/_layout/teacher/courses/$course": {
      "filePath": "_layout.teacher.courses.$course.tsx",
      "parent": "/_layout/teacher/courses"
    },
    "/_layout/student/education/": {
      "filePath": "_layout.student.education.index.tsx",
      "parent": "/_layout/student"
    },
    "/_layout/curator/$course/$lesson/homeworks": {
      "filePath": "_layout.curator_.$course.$lesson.homeworks.tsx",
      "parent": "/_layout"
    },
    "/_layout/student/education/$course/$lesson": {
      "filePath": "_layout.student.education.$course.$lesson.tsx",
      "parent": "/_layout/student"
    },
    "/_layout/student/education/$course/": {
      "filePath": "_layout.student.education.$course.index.tsx",
      "parent": "/_layout/student"
    }
  }
}
ROUTE_MANIFEST_END */
